### ISSUE TITLE
Packaging/versioning/maintenance policy

### ISSUE THREAD

**Issue by untitaker** [pallets/meta#10]
- Backwards compat is key
- Semver should be followed
- Use milestones to mark the next-possible release where the change can be made

**Comment by untitaker** [comment]
However, it is also the case that bumping e.g. Jinja from 2.0 to 3.0 should IMO never happen, as Python's packaging tools are completely unaware of semver and will silently upgrade to the major version. Better to have a new `jinja3` package. But maybe Python's packaging tools catch up until then, you never know.

**Comment by jeffwidman** [comment]
> Backwards compat is key

One possible way to handle changes that everyone agrees should be fixed (https://github.com/pallets/jinja/issues/119, https://github.com/pallets/jinja/issues/379) is put them behind a feature flag that defaults to disabled. It adds cruft, but also lets folks use the new behavior now, which makes the eventual migration to the next major release less painful. If we go this route, it should only be allowed for small obvious changes though.

Opinions on this?

**Comment by davidism** [comment]
I'm ok with pushing new major versions, as long as changes are communicated well in advance.  I don't think separate packages solves the problem.

Now we're in this weird situation where the library is referred to as "jinja", the website is "jinja.pocoo.org", and yet the package to install is "jinja2", even though a "jinja" package exists and doesn't say anything when it gets installed instead (at least in py2, it fails in py3).

It's pretty easy to add a warning to `setup.py` if we detect `jinja < 3` when installing `jinja >= 3`.  You could even make this abort with "please uninstall version 2 first" to make extra sure they're aware of it.

~~~python
from pkg_resources import get_distribution, parse_version
if get_distribution('jinja2').parsed_version < parse_version('3'):
    print('You are trying to install Jinja version 3.  It contains breaking changes from version 2.')
    print('Uninstall Jinja2 first before continuing.  Verify that your code works with version 3.')
    sys.exit(1)
~~~

**Comment by davidism** [comment]
Ideally, we'd go back to using the Jinja package, and add a dummy package to Jinja2 at some point that tells people to install Jinja from now on.  We'd upload to both for a while to smooth the initial transition.

**Comment by untitaker** [comment]
@davidism It makes no sense to release version 3 of the `jinja2` package. Of course reusing `jinja` would be "aesthetically" the right choice, but unfortunately it is very cumbersome in practice due to the packaging tools' behavior.

**Comment by davidism** [comment]
Click isn't releasing separate packages for each major version, and appears to be doing fine.  I'd rather take the burden if it means fixing the situation.

**Comment by untitaker** [comment]
Click's releases didn't actually contain any compat-breaking changes so far.

**Comment by davidism** [comment]
Which would make it even more confusing if one suddenly did, and a new package called click15 was created.  Like I said above, I think this can be handled without splitting packages up.

**Comment by jeffwidman** [comment]
It's standard practice in the python world to stay with the same PyPI namespace even for major version upgrades. Off the top of my head, I can't think of a project that switches package names when a major version is released. 

I agree that backwards-incompatible changes are a little more sensitive for Jinja since it's a dependency on projects like Ansible where there's a lot of users unfamiliar with Python who probably aren't pinning their underlying dependencies. 

However, since it's so easy to add warnings via `setup.py` (I wasn't aware you could do that, neat trick!), I prefer we stick with existing package names and just follow standard semvar of major version indicates backwards-incompatible changes.

I'm also in favor of cleaning up things by switching back to `jinja`.

**Comment by untitaker** [comment]
@jeffwidman We're not going to implement half a package manager in Jinja's setup.py. Also this has no effect when installing software that was intended for use with Jinja2 from scratch.

**Comment by davidism** [comment]
I think we'd have to write a *few* more lines to reach "half a [package manger](https://github.com/pypa/pip/tree/develop/pip)". ;-)

**Comment by RonnyPfannschmidt** [comment]
also since now we have manylinux, building wheels is more predominant

we might want to take a look at auto-upload of wheels for osx, windows and manylinux
