### ISSUE TITLE
Move some repos to pallets

### ISSUE THREAD

**Issue by untitaker** [pallets/meta#13]
- [x]  https://github.com/mitsuhiko/flask-sphinx-themes
- [ ] https://github.com/mitsuhiko/flask-feedback
- [x] https://github.com/mitsuhiko/flask-website

**Comment by mitsuhiko** [comment]
Will move.

**Comment by mitsuhiko** [comment]
Do we need the feedback repo still?

**Comment by untitaker** [comment]
I mean, just for archival.

On 13 April 2016 19:16:22 CEST, Armin Ronacher <notifications@github.com> wrote:
>Do we need the feedback repo still?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/meta/issues/13#issuecomment-209550894

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jeffwidman** [comment]
I'd just drop the feedback repo personally. It looks like it hasn't been used in years, and if we were to start doing this again, I'd vote to just use an external hosted tool as it's one less thing to maintain. With the switch to `pallets`, feels like an ideal time for a clean break.

**Comment by mitsuhiko** [comment]
I will leave the repo there just to discourage people to find it. We don't have private repos on pallets yet.

**Comment by untitaker** [comment]
Then please create a `pallets-archive` for unmaintained code. I feel like this is equivalent to deleting old blogposts you no longer agree with.

**Comment by mitsuhiko** [comment]
Is there a specific reason this cannot just linger on my user account? I mean, there is no point in touching this.

**Comment by untitaker** [comment]
Not that strong of an opinion, but I think it'd categorically belong to the pallets project.
