### ISSUE TITLE
Switch all sites to readthedocs

### ISSUE THREAD

**Issue by untitaker** [pallets/meta#15]
We discussed this extensively before. I think it's time to act. For each project `foo`:
- Set up `foo.palletsprojects.com`, which is an alternative hostname for a simple RTD site. This requires a CNAME entry to `pallets-foo.readthedocs.io`. Do not use wildcard DNS entries.
- Set up maintenance and `master` branches to be built.
- Disable `stable` build, disable `latest` build
- The latest maintenance branch is marked as "default" to redirect from `/` to.

Bonus:
- Set up rewrite rules on pocoo.org to redirect from e.g. `http://flask.pocoo.org/docs/0.10/` to `https://flask.palletsprojects.org/en/0.10-maintenance/`. This is not hard and can be done within a htaccess even.

---

Other policies:
- For every major release/new maintenance branch, it needs to be manually enabled in the RTD admin.
- All doc fixes except the worst factual inaccuracies go to `master`.

cc @pallets/global-committers

**Comment by untitaker** [comment]
All of this is under the assumption we already know we want to switch to RTD. I'd prefer a separate thread if we need to discuss it again, i.e. I want to separate discussion/planning.

**Comment by untitaker** [comment]
I've registered ReadTheDocs names for various projects: https://readthedocs.org/profiles/untitaker/

**Comment by untitaker** [comment]
I suggest for testing RTD stability we start with Click:

* Not as significant as Flask or Werkzeug, so larger tolerance if things break.
* Frequent major releases.

@mitsuhiko As ReadTheDocs doesn't support SSL, we need a proxy from `click.palletsprojects.com` to `pocoo-click.readthedocs.io`. Here are the docs: https://docs.readthedocs.io/en/latest/alternate_domains.html

**Comment by mitsuhiko** [comment]
I will look into how to best achieve this.

**Comment by jeffwidman** [comment]
@mitsuhiko Had any time to look into this?

**Comment by davidism** [comment]
* Flask
    * https://flask.rtfd.io - owned by @mitsuhiko, @kennethreitz
    * ~https://pallets-flask.rtfd.io~ - 404
    * ~https://new78kxhn.rtfd.io/~ - "import project" for Flask says it's owned by this random user, but it 404s
* Werkzeug
    * https://werkzeug.rtfd.io - owned by @dag
    * https://pallets-werkzeug.rtfd.io - owned by @untitaker
* Click
    * https://click.rtfd.io - owned by @cjwatson
    * https://pallets-click.rtfd.io - owned by @mitsuhiko, @untitaker
* Jinja
    * ~https://jinja.rtfd.io~ - 404
    * https://pallets-jinja.rtfd.io - owned by @untitaker
    * https://jinja2.rtfd.io - owned by random user
    * ~https://pallets-jinja2.rtfd.io~ - 404
* MarkupSafe
    * ~https://markupsafe.rtfd.io~ - 404
    * https://pallets-markupsafe.rtfd.io - owned by @untitaker 
* ItsDangerous
    * https://itsdangerous.rtfd.io - owned by @windfarer, non-English
    * https://pallets-itsdangerous.rtfd.io - owned by @untitaker

**Comment by davidism** [comment]
All of these are very out of date. Some are not styled properly. One is in another language.

We'd be using the [palletsprojects.com](https://www.palletsprojects.com) domain, but it would still be nice to unify these to reduce confusion.

**Comment by ThiefMaster** [comment]
Not a fan of the `pallets-*` prefixes for the RTD pages.

I think we should ask people who run unofficial RTD mirrors on official-looking names to take them down. Especially if they are not even in English...

**Comment by davidism** [comment]
Pinging the RTD support team: @ericholscher, @agjohnson, @humitos. We would like to take ownership of the project names listed above. What is the process?

**Comment by mitsuhiko** [comment]
If we go with rtd we should figure out what the story is with the different branches. Last time managing themes across different branches was tricky and the inter branch links did not properly work.

**Comment by cjwatson** [comment]
I'm willing to rename `click` out of the way on RTD so that pallets/click can take it over, but would appreciate some time to chase up references to the older name.  Is there some reasonable way to have both `click` and `click-package` work for that project for a transitional period?

**Comment by davidism** [comment]
* https://pocoo-click.readthedocs.io - owned by @lovesky or possibly @moskytw

None of the other `pocoo-` names are registered.

**Comment by Windfarer** [comment]
I'm the owner of Chinese translation of ItsDangerous documentation, I can return that documentation space if you need it.

**Comment by davidism** [comment]
@cjwatson oh, I didn't stop long enough to notice it wasn't the same Click. Thanks for being open to it though. There doesn't appear to be a nice way to do a subdomain redirect, unfortunately.

If that's the primary documentation for your project and the project is still ongoing, I'm ok with leaving the name to you, since it's clear that it's separate from our Click.

**Comment by untitaker** [comment]
Since we're going to use our own domains the rtd URL should be irrelevant.

**Comment by davidism** [comment]
@untitaker the thing I'm concerned with is confusion. I've seen users who are having problems because they thought the RTD version was official (since it is for a lot of projects).

**Comment by davidism** [comment]
@Windfarer RTD supports translations, and it would be nice to keep the work you've done. Let's try adding me to the itsdangerous name, and following the [docs](https://docs.readthedocs.io/en/latest/localization.html) on linking a translation.

**Comment by Windfarer** [comment]
@davidism I've added you as the maintainer, edit it as you wish, and I will update my translation later.

**Comment by cjwatson** [comment]
@davidism The name conflict has been kind of unfortunate for a while.  However, my click is an end-of-life project (still being maintained to some extent, but phasing out), so it may make sense to move it anyway.  I'll see what we can do.

**Comment by ericholscher** [comment]
We don't have a formal process, but I can help with this. We generally recommend reaching out to the owners and asking them to switch. In cases where the namespace isn't used for some other official project, we can generally transfer the name, assuming someone else just uploaded the actual   projects docs there.

In general we have a hard time with namespaces, since multiple languages/communities use RTD. Also, PyPI doesn't have OAuth, so there isn't really a way to programmatically infer ownership of even the Python namespace.

**Comment by davidism** [comment]
@ericholscher is there a more direct and private way I can get in contact with the owners than by pings here? A couple of them didn't have obvious GitHub accounts either.

**Comment by ericholscher** [comment]
Not currently. `mirror`is an account we control, which is inactive, and I can transfer personally.

I wonder if we could build in a "request ownership" mechanism into RTD itself, which would email the folks, and provide them a simple way to transfer or add ownership.

**Comment by jeffwidman** [comment]
What are the next actions at this point to close out this issue? 

@davidism any chance you can move your list from https://github.com/pallets/meta/issues/15#issuecomment-308127069 into the top post of this issue and update it? I think that'd make it more clear which projects still need migration... I would, but I don't have the proper permissions on this repo.

**Comment by davidism** [comment]
@ericholscher I'd like to take control of the jinja2 docs owned by mirror. Would you be able to transfer that or should I contact someone else at Read The Docs?

Also, I'd like to figure out a way to consolidate "pallets-jinja" and "jinja2" into "jinja" which doesn't exist yet. I can't figure out how to create a RTD page since Jinja is already imported. What can I do to rename / redirect these?

**Comment by ericholscher** [comment]
Yea, I can set it up -- the renames & redirects will be manual on my side. Do you want to do it nowish?

**Comment by davidism** [comment]
Sure, I can do it now. We'd like to rename/redirect `pallets-jinja` to `jinja`, and have `jinja2` redirect to `jinja`.

**Comment by davidism** [comment]
I'll want to go through the process for our other packages too, but I'm going to start out with Jinja and getting everything building correctly.

**Comment by ericholscher** [comment]
Should be done.

**Comment by davidism** [comment]
Awesome, thank you!

**Comment by ericholscher** [comment]
Redirects everywhere now.

**Comment by ericholscher** [comment]
Confirmed with:

-> curl -IL pallets-jinja.readthedocs.io/
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.10.3 (Ubuntu)
X-Deity: web04
Content-Type: text/html
Date: Wed, 08 Nov 2017 23:08:34 GMT
Location: https://jinja.readthedocs.io/
Connection: keep-alive
Content-Length: 170

```

**Comment by lepture** [comment]
FYI, I've bought `python-flask.org`.

**Comment by kennethreitz** [comment]
I don't have access.

**Comment by ericholscher** [comment]
I've added the redirects in a PR on our side. They will be deployed early next week.

**Comment by davidism** [comment]
@cjwatson sorry for the last minute ping, but I'm working on deploying Click's docs to RTD today. Would you be willing to make the switch? I'd be happy to add a "Looking for Ubuntu Click? Go here:" message to the top. If you'd like to chat I'm @davidism on Twitter.
