### ISSUE TITLE
Do something about the pocoo flask repos

### ISSUE THREAD

**Issue by jeffwidman** [pallets/meta#20]
- [ ] https://github.com/pocoo/powered-by-flask
- [ ] https://github.com/pocoo/metaflask

It's not clear how these relate/differ from the repo's in the Pallets org.

There's a number of ways to handle this, including moving to Pallets, updating the status of those repos to point to the new repos, simply marking as archived, etc. 

Personally, I'd archive the powered-by-flask as I don't think it's worth maintaining a separate repo. Instead, add a page to the existing Flask docs that lists major websites using Flask.

Similarly, I'd mark the metaflask repo as archived, not sure we want the maintenance chore of keeping that info updated.

Input?

**Comment by jeffwidman** [comment]
Can these repos both be killed? They're dead in the water and just add confusion for people new to the flask ecosystem.

**Comment by untitaker** [comment]
I dislike the idea of having powered-by-flask in the docs. There is no version-dependent information in that dataset.

Moving to pallets sounds OK. metaflask is most likely dead in the water.

**Comment by davidism** [comment]
I plan to resurrect Powered by Flask as "Powered by Pallets" on the new website. That one can be shut down, it's not maintained anyway.

**Comment by davidism** [comment]
metaflask is now this repo, except without the signup, that can be shut down as well

**Comment by jeffwidman** [comment]
Since it seems we are all in agreement that both of these repos can be deleted, what is the next action to do that? 

@untitaker / @davidism Are either of you owners of that repo or does @mitsuhiko need to do it?

**Comment by mitsuhiko** [comment]
I would propose we move it to pallets and make them private.

**Comment by davidism** [comment]
@mitsuhiko looks like all 7 (visible to me) pocoo repos should be moved to pallets, they're all Flask related.

**Comment by mitsuhiko** [comment]
All transferred!

**Comment by jeffwidman** [comment]
Thanks for the quick turnaround @mitsuhiko

**Comment by jeffwidman** [comment]
Shouldn't https://github.com/pallets/powered-by-flask-bot be made private since https://github.com/pallets/powered-by-flask is now private?

**Comment by jeffwidman** [comment]
Shouldn't https://github.com/pallets/powered-by-flask-bot be made private since https://github.com/pallets/powered-by-flask is private?

**Comment by mitsuhiko** [comment]
Done :)

**Comment by jeffwidman** [comment]
Thanks!
