### ISSUE TITLE
Make it easy for people to report security vulnerabilites

### ISSUE THREAD

**Issue by jeffwidman** [pallets/meta#21]
Per https://github.com/pallets/werkzeug/pull/1001#issuecomment-243942898

Not sure how to solve this, but I do agree it's not clear how someone should report a security vulnerability. I just pulled up palletsproject.org and there's no obvious "security" link in the footer or elsewhere. 

Would also be good to have a clear link on each project's readme. Either an email address or a link to palletsproject.org/security etc

Thoughts?

**Comment by untitaker** [comment]
We should have an email address that just forwards the email to a list of contacts.

**Comment by jeffwidman** [comment]
What's the next action here?

**Comment by untitaker** [comment]
Yes only @mitsuhiko can do that, though I believe the one at https://www.palletsprojects.com/governance/rules-of-engagement/ is sufficient for both situations. So in fact it would only require a PR against the website repo, which automatically deploys.

**Comment by davidism** [comment]
I guess that page already worked at least once, since that Jinja `.format` bug was handled without a bug report here, unless he just saw that elsewhere himself. I would like an alias though, so that we can all see these communications.

**Comment by untitaker** [comment]
I suspect people just email Armin directly, but that barely scales.

**Comment by davidism** [comment]
Duplicate of #3
