### ISSUE TITLE
Flask repo contains tags referencing Jinja repo

### ISSUE THREAD

**Issue by davidism** [pallets/meta#22]
https://github.com/pallets/flask/tree/2.7.3
https://github.com/pallets/flask/commit/762c612e7276889aac265645da00e62e33d1573c

Not sure how this happened, maybe someone added a flask remote to their Jinja repo by accident. Only tags reference them, branch names didn't get in.

`fetch` doesn't fetch the tags in my existing repository, and the commits aren't pulled, because the tags aren't reachable from the tree in my repo. But cloning a fresh copy does grab all the tags and commits.

**Comment by davidism** [comment]
I'm going to delete the tags and hope that GitHub garbage collects the commits eventually. Just waiting to get out of this meeting.

**Comment by davidism** [comment]
Here is a list of refs and tags before I remove anything.
[tag_refs.txt](https://github.com/pallets/meta/files/945077/tag_refs.txt)

**Comment by jeffwidman** [comment]
Good catch
