### ISSUE TITLE
Unify the configuration in each project

### ISSUE THREAD

**Issue by davidism** [pallets/meta#23]
Currently, each project has its own slightly different version of:

- tox.ini
- .travis.yml
- .coveragerc
- setup.cfg
- Makefile
- docs/conf.py
- docs/Makefile

I recently spent time updating Flask's configuration to provide a sane set of Travis jobs and branch coverage with CodeCov. Let's use that as a base for all projects.

It would also be good to investigate MacOS tests on Travis and Windows tests on Appveyor.

To start, I just want to update each individual repository, although it would be nice to set up a workflow to keep the configurations in sync.

**Comment by ThiefMaster** [comment]
Adding .editorconfig and .isort.yml configs would be a good idea too.

**Comment by davidism** [comment]
Agreed, I'm open to adding other tools. Adding a lint configuration would be good too, although it's only feasible to enable it on Flask, MarkupSafe, and ItsDangerous right now since they have few to no open PRs.
