### ISSUE TITLE
Drop 2.6 (and 3.3?) support

### ISSUE THREAD

**Issue by davidism** [pallets/meta#24]
Wheel no longer supports 2.6, which causes a bunch of issues installing things that don't upload 2.6 wheels already to PyPI. Pip warns about dropping support. Tox mentions in tox-dev/tox#679 that setuptools is dropping support, and therefore they want to also. The codecov library uses argparse, which doesn't exist in 2.6.

Basically, all the tooling we rely on is dropping support. Every time another thing fails I have to hunt around trying to figure out how to fix it. This is not a very good use of my time.

PyPInfo reports that 10_976 / 2_345_199 Flask installs in the last month were 2.6. That's only 0.4%, and I have a feeling most of that is tests running in 2.6 envs.

**Comment by davidism** [comment]
py, a dependency of pytest, just dropped support for 2.6 *and* 3.3, so now there's errors on all our projects for that too.

**Comment by davidism** [comment]
cc @RonnyPfannschmidt

**Comment by ThiefMaster** [comment]
I won't miss it. I guess people who need 2.6 support can simple use the last released versions?

**Comment by RonnyPfannschmidt** [comment]
from my pov its not at all unreasonable to drop eol python versions - in particular 2.6 had quite a share of strange issues/workarounds for pytest/pylib

**Comment by davidism** [comment]
How do we drop support? Do we make new releases that say "this is the last one to support 2.6 / 3.3"? Do we just stop testing them?

**Comment by ThiefMaster** [comment]
I'd do a minor release with whatever bugfixes etc there are since the last release that officially deprecates these versions, then remove support/workarounds for them in the next release after that.

I think technically with semver there should be a major version number increment when dropping support for a Python version, but Flask being pre-1.0 doesn't require it, and bumping e.g. Jinja to 3.0 just for that feels wrong. I'd rather keep that for the day Python 2 support goes out of the window...

**Comment by davidism** [comment]
The problem is that all our tools are breaking *now*. Deprecating our support doesn't fix any of the problems I'm running into.

**Comment by ThiefMaster** [comment]
It's just tests that break, right? If this is mainly tox, we could re-run the tests manually with an older pytest/tox/.. a last time to know the release is OK, and ignore the CI test status for those releases

**Comment by davidism** [comment]
So remove the Travis builds for those versions, but still tox test them locally? That would work for me.

**Comment by RonnyPfannschmidt** [comment]
what you can always do is pin pytest version and tox versions

**Comment by davidism** [comment]
Unfortunately that doesn't work inside Tox, which can't distinguish between installing build deps and install deps.

**Comment by RonnyPfannschmidt** [comment]
@davidism i recall this can be elevated by pinning the virtualenv version, as well as setting up the deps listing with extra elements, however they need to match and either fit for all envs or fit for specific ones

**Comment by hugovk** [comment]
Here's the pip installs for Flask from PyPI for the last month (via `pypinfo --percent --pip flask pyversion`)

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   61.7% |      1,384,878 |
| 3.6            |   18.2% |        409,379 |
| 3.5            |   15.1% |        339,973 |
| 3.4            |    4.4% |         97,672 |
| 2.6            |    0.4% |          9,300 |
| 3.3            |    0.1% |          2,130 |
| 3.7            |    0.1% |          1,835 |
| 3.2            |    0.0% |            132 |
| None           |    0.0% |             16 |

Strictly speaking, [semver](https://github.com/semver/semver/blob/master/semver.md#how-should-i-handle-deprecating-functionality) says to make a minor release with a deprecation warning, then a major with removal.

In practice, many have just been making a release with 2.6(/3.3) removal, sometimes as major, sometimes as minor. I think major is generally better.

Only testing locally to retain 2.6/3.3 sounds like a quite a hassle for little (0.5%) benefit, especially as it moves the burden of automated CI testing of contributions onto maintainers.

**Comment by lepture** [comment]
Should we agree to remove CI for 2.6 and 3.3 in all projects? If not, CI will fail all the time.

**Comment by davidism** [comment]
Yes, definitely, please start removing them on master branches. Maintenance branches are a bit trickier, as they may still "support" 2.6 and 3.3. What I did with Flask was to remove the envs, but still test it locally with a 2.6 configuration I had that still worked.

A general goal is #23 to make the project configurations more consistent. For pytest, coverage, and tox (and probably everything else) use Flask as a template, I've got that basically where I want it.

**Comment by lepture** [comment]
No sure how to unify them together since there are always differences. Here in click's tox file:

```
setenv =
    # pytest 3.3+ does not support Python 2.6 and 3.3 anymore.
    py26,py33: _CLICK_TEST_PYTEST_DEP=pytest<3.3
```

Should I drop it?

**Comment by davidism** [comment]
Not literally unify, although that might be an interesting problem to solve. Just in terms of using the same configurations and layouts.

Yes, I'd remove that from Click.
