### ISSUE TITLE
Pin versions to avoid major updates of dependencies

### ISSUE THREAD

**Issue by davidism** [pallets/meta#25]
Moving this from pallets/flask#2954.

@ThiefMaster posted:

> Currently we set minimum versions only, with no maximum version requirement. Should we prevent implicit updates to new major versions of any of our dependencies?

**Comment by davidism** [comment]
If we put upper limits in place, it means that even if the newer version doesn't cause any issues, or at least any issues relevant to a project, that project still can't upgrade. Pip allows but keeps warning about version mismatches if you force version upgrades.

This could be solved by making  releases that just re-pin dependency versions. But then we're in the same situation, there will be plenty of projects that weren't pinned and will have the same issue.

What is the version bump for a pin update? Major? It caused breaking changes (in this case, for specific use cases), but we're not going to release Flask 2.0 for It's Dangerous 1.0. Minor? Maybe, but that brings in the baggage of making a significant release, when we might not be ready for that. Patch? Then exact versions would have to be pinned, since `~` would upgrade to those automatically still.

**Comment by ThiefMaster** [comment]
I wonder what kind of pinning people use for Flask... Personally I pin exact versions for everything and do a manual update from time to time (after checking changelogs in case of non-patch version bumps, especially if the major version changed).

So my gut feeling would be to do a minor release to bump dependency version pins.

**Comment by davidism** [comment]
I would love to have better release schedules and policies, but the unfortunate reality is that there are few maintainers with limited time. We're working to change that, but there's been little progress yet.

Making a release is already a long process that requires checking and coordinating a lot of parts. Creating extra releases to bump versions adds to that.

**Comment by benvand** [comment]
By not pinning at all then you're susceptible to major version changes to your dependencies being brought in with a fresh install.
Assuming your dependencies are following semantic versioning major version bumps _should_ contain 'incompatible api changes'.
This means you cannot depend on using the same interface to work with the dependency between 2 major version upgrades.

What this currently means for Flask, in practice, is that any of your dependencies can make a major version release breaking the api with which flask communicates and flask will automatically install it and try to use it. This could result in breaking new installs entirely for example.

If you don't pin the dependencies now, and the above happens in the future, you could be _forced_ to make a short notice major release pinning your dependencies to specific versions.

There are big benefits to Flask and Pallets in pinning your dependencies below major version bumps. Granted Flasks dependencies are all managed by Pallet but even in terms of best practice making sure your app will not bring in dependencies whose api have wholly changed is recommended.
Then as part of the minor release process update dependencies. Sure it's not ideal, but the alternative is having people install your software and it not running.

**Comment by davidism** [comment]
See also pallets/flask#2586, a discussion from January about bumping minimum versions and how to track versions in Flask.

**Comment by jeffwidman** [comment]
I would prefer to let application users pin their versions and not pin versions in libraries except for known incompatibilities. 

Yes, from time to time something will break, but I don't like the alternative of handcuffing users' versions. If they want to quickly upgrade a dependency, let them.

The frequency that something breaks in a dependency is low, and most maintainers are quick to fix bugs and cut a new release when something is truly breaking. Plus it only take one time for someone to realize they need to be pinning exact versions of everything from the application level.

**Comment by davidism** [comment]
Decision after meeting with @mitsuhiko is that pinning max versions is impracticle. I agree with him and @jeffwidman. Instead, we should focus on making upgrade / deprecation paths well documented.
