### ISSUE TITLE
Private Infrastructure

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/meta#3]
Generally I would like to keep pallets as public as possible.  There are three areas I can see for which this does not work:
- Credentials. Be it server access, pypi fallback account etc.  All this sort of stuff just cannot be public.  We probably will be able to use private github repositories for this.
- Security mailinglist: need to figure out where to host this.  Currently this goes into my personal google apps account
- Community reports: this is a mailinglist for community members that want to reach out because of bad behavior on the issue tracker or elsewhere.

The two mailinglists we need to find a place that we can use.

**Comment by davidism** [comment]
For credentials we could use Keybase team file sharing. Create a team with the core maintainers, we can add files for keepassxc / pass.

**Comment by davidism** [comment]
@mitsuhiko will create a gsuite account for Pallets over the weekend, then each of the maintainers will get an account with correct permissions. We can set up group alias emails with that.

**Comment by davidism** [comment]
Thinking of setting up HashiCorp Vault for managing access to credentials.
