### ISSUE TITLE
Group email that forwards to all members

### ISSUE THREAD

**Issue by davidism** [pallets/meta#4]
Over in the SO Python room, we have an email, `chatroom@sopython.com`, that forwards to all the owners.  This lets users get in contact with us quickly and privately and lets all of us see the conversation even if only one of us handles it.  We should have a `team@palletsproject.com` that does the same thing.

**Comment by untitaker** [comment]
The email at https://www.palletsprojects.com/governance/rules-of-engagement/ probably should redirect to the email addresses of the users on the `Moderators` team I've created yesterday.

**Comment by davidism** [comment]
Duplicate of #3

**Comment by jeffwidman** [comment]
@davidism up to you, but I personally find it easier to track separate issues rather then one mega-issue like #3. Handling credentials is pretty different from email lists. And there may be additional subtasks required for them... in one big github issue it's easy to lose track of the details.
