### ISSUE TITLE
Release Flask 0.10.2 soonish

### ISSUE THREAD

**Issue by untitaker** [pallets/meta#5]
It already contains a lot of bugfixes, and is probably a cheaper shot at just "a next release" than 0.11 or 1.0.

cc @pallets/global-committers

**Comment by untitaker** [comment]
See also https://github.com/pallets/flask/issues/1324#issuecomment-205854141

**Comment by jeffwidman** [comment]
The title should probably include "Flask"

**Comment by untitaker** [comment]
whatever, 0.11 is out.
